In [19]:
import pandas as pd
import numpy as np

In [25]:
df= pd.read_csv('pesquisa_satisfacao.csv', sep= ';')
(df)
df.head(3)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 22: invalid start byte

In [ ]:
media_satisfacao = df.groupby('Satisfação')['Tempo de Espera(min)'].mean().resert_index()
media_satisfacao['Tempo de Espera(min)']=round(media_satisfacao['Tempo de Espera (min)'])
media_satisfacao

AttributeError: 'Series' object has no attribute 'resert_index'

In [ ]:
df_anp=pd.read_csv('ca-2005-01.csv', sep=';')
df_anp

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,SE,SP,GUARULHOS,AUTO POSTO SAKAMOTO LTDA,49.051.667/0001-02,RODOVIA PRESIDENTE DUTRA,S/N,"KM 210,5-SENT SP/RJ",BONSUCESSO,07178-580,GASOLINA,04/01/2005,"2,257","1,9594",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
1,SE,SP,GUARULHOS,AUTO POSTO SAKAMOTO LTDA,49.051.667/0001-02,RODOVIA PRESIDENTE DUTRA,S/N,"KM 210,5-SENT SP/RJ",BONSUCESSO,07178-580,ETANOL,04/01/2005,"1,449","1,0962",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
2,SE,SP,GUARULHOS,AUTO POSTO SAKAMOTO LTDA,49.051.667/0001-02,RODOVIA PRESIDENTE DUTRA,S/N,"KM 210,5-SENT SP/RJ",BONSUCESSO,07178-580,DIESEL,04/01/2005,"1,579","1,4444",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
3,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,GASOLINA,04/01/2005,"2,21","1,97",R$ / litro,BRANCA
4,SE,SP,SOROCABA,COMPETRO COMERCIO E DISTRIBUICAO DE DERIVADOS ...,00.003.188/0001-21,RUA HUMBERTO DE CAMPOS,306,NaN,JARDIM ZULMIRA,18061-000,ETANOL,04/01/2005,"1,23","0,93",R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912724,NE,BA,LIVRAMENTO DE NOSSA SENHORA,AUTO POSTO PIRES PEREIRA LTDA,02.253.236/0001-65,AVENIDA LINDEMBERG CARDOSO,667,COMODO,TAQUARI,46140-000,ETANOL,27/06/2005,"1,98",NaN,R$ / litro,PETROBAHIA
912725,NE,BA,LIVRAMENTO DE NOSSA SENHORA,AUTO POSTO PIRES PEREIRA LTDA,02.253.236/0001-65,AVENIDA LINDEMBERG CARDOSO,667,COMODO,TAQUARI,46140-000,DIESEL,27/06/2005,"1,69",NaN,R$ / litro,PETROBAHIA
912726,NE,BA,LIVRAMENTO DE NOSSA SENHORA,AUTO POSTO 5 DE FEVEREIRO LTDA,02.125.226/0001-44,PRACA CORONEL ZEZINHO TANAJURA,1,COMODO,CENTRO,46140-000,GASOLINA,27/06/2005,"2,5",NaN,R$ / litro,PETROBAHIA
912727,NE,BA,LIVRAMENTO DE NOSSA SENHORA,AUTO POSTO 5 DE FEVEREIRO LTDA,02.125.226/0001-44,PRACA CORONEL ZEZINHO TANAJURA,1,COMODO,CENTRO,46140-000,ETANOL,27/06/2005,"1,95",NaN,R$ / litro,PETROBAHIA
912728,NE,BA,LIVRAMENTO DE NOSSA SENHORA,AUTO POSTO 5 DE FEVEREIRO LTDA,02.125.226/0001-44,PRACA CORONEL ZEZINHO TANAJURA,1,COMODO,CENTRO,46140-000,DIESEL,27/06/2005,"1,69",NaN,R$ / litro,PETROBAHIA

In [ ]:
df_anp_rj = df_anp.loc[df_anp['Estado - Sigla'] == 'RJ']
df_anp_rj.head(5)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
12,SE,RJ,NITEROI,PETROBRAS DISTRIBUIDORA S.A.,34.274.233/0033-81,AVENIDA ROBERTO SILVEIRA,205,NaN,ICARAÍ,24230-151,GASOLINA,04/01/2005,"2,289",NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
13,SE,RJ,NITEROI,PETROBRAS DISTRIBUIDORA S.A.,34.274.233/0033-81,AVENIDA ROBERTO SILVEIRA,205,NaN,ICARAÍ,24230-151,ETANOL,04/01/2005,"1,599",NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
14,SE,RJ,MACAE,PETROBRAS DISTRIBUIDORA S.A.,34.274.233/0052-44,RUA CONSELHEIRO ALMEIDA PEREIRA,303,NaN,PRAIA CAMPISTA,27923-510,GASOLINA,04/01/2005,"2,328","2,1136",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
15,SE,RJ,MACAE,PETROBRAS DISTRIBUIDORA S.A.,34.274.233/0052-44,RUA CONSELHEIRO ALMEIDA PEREIRA,303,NaN,PRAIA CAMPISTA,27923-510,ETANOL,04/01/2005,"1,687","1,4259",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.
16,SE,RJ,MACAE,PETROBRAS DISTRIBUIDORA S.A.,34.274.233/0052-44,RUA CONSELHEIRO ALMEIDA PEREIRA,303,NaN,PRAIA CAMPISTA,27923-510,DIESEL,04/01/2005,"1,606","1,4307",R$ / litro,PETROBRAS DISTRIBUIDORA S.A.

In [ ]:
df_anp_rj['Valor de Venda']=df_anp_rj['Valor de Venda'].str.replace(',', '.').astype(float)

C:\Users\celso.gomes\AppData\Local\Temp\ipykernel_26768\2610844079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_anp_rj['Valor de Venda']=df_anp_rj['Valor de Venda'].str.replace(',', '.').astype(float)

In [ ]:
media_munic_rj=df_anp_rj.groupby('Municipio')['Valor de Venda'].mean().reset_index()
media_munic_rj = media_munic_rj.sort_values(by='Valor de Venda', ascending=False)
media_munic_rj

                      Municipio  Valor de Venda
22                       PARATY        2.046755
0                ANGRA DOS REIS        2.025708
14                  MANGARATIBA        2.023748
33              SAO JOSE DE UBA        2.016154
16                     MESQUITA        1.960870
37                  TERESOPOLIS        1.951446
35                    SAQUAREMA        1.935836
39                      VALENCA        1.935772
34                     SAPUCAIA        1.930971
24                   PETROPOLIS        1.929837
2            ARMACAO DOS BUZIOS        1.920374
19                NOVA FRIBURGO        1.908377
38                    TRES RIOS        1.906549
15                       MARICA        1.906101
21               PARAIBA DO SUL        1.893178
12                        MACAE        1.886574
11                    ITAPERUNA        1.883456
41                VOLTA REDONDA        1.880727
1                      ARARUAMA        1.880255
23              PATY DO ALFERES        1.870256
18                      NITEROI        1.867720
40                    VASSOURAS        1.856202
13                         MAGE        1.847169
25                    QUEIMADOS        1.841286
6                     CABO FRIO        1.826392
3                BARRA DO PIRAI        1.822731
36                   SEROPEDICA        1.817769
30  SAO FRANCISCO DE ITABAPOANA        1.817061
4                   BARRA MANSA        1.815369
26                      RESENDE        1.810762
27                   RIO BONITO        1.804962
29       SANTO ANTONIO DE PADUA        1.795913
17                    NILOPOLIS        1.792817
7         CAMPOS DOS GOYTACAZES        1.780938
10                      ITAGUAI        1.772167
31                  SAO GONCALO        1.760827
5                  BELFORD ROXO        1.746792
32           SAO JOAO DE MERITI        1.738916
28               RIO DE JANEIRO        1.726500
20                  NOVA IGUACU        1.710546
8               DUQUE DE CAXIAS        1.710019
9                      ITABORAI        1.700943

In [ ]:
array_valor_venda=np.array(media_munic_rj['Valor de Venda'])

In [ ]:
media = np.mean(array_valor_venda)
mediana = np.median(array_valor_venda)
q1 = np.quantile(array_valor_venda,0.25)
q2 = np.quantile(array_valor_venda,0.50)
q3 = np.quantile(array_valor_venda,0.75)
print(f'A média é {media}')
print(f'A mediana é {mediana}')
print(f'Primeiro quartil (Q1): {q1}')
print(f'Segundo quartil (Q2, Mediana): {q2}')
print(f'Terceiro quartil (Q3): {q3}')

A média é 1.858493924321496
A mediana é 1.8619606638132185
Primeiro quartil (Q1): 1.7981754885377697
Segundo quartil (Q2, Mediana): 1.8619606638132185
Terceiro quartil (Q3): 1.9173751159644377

In [ ]:
munic_acima_q3 = media_munic_rj.loc[media_munic_rj['Valor de Venda']>q3] 
munic_acima_q3

NameError: name 'media_munic_rj' is not defined

In [ ]:
df_rj_etanol = df_anp.loc[(df_anp['Municipio'] == 'RIO DE JANEIRO') & (df_anp['Produto'] == 'ETANOL')]
df_rj_etanol

NameError: name 'df_anp' is not defined